config/routes.rb
Rails.application.routes.draw do

  as :user do
    get '/register', to: 'devise/registrations#new', as: :register
    get '/login', to: 'devise/sessions#new', as: :login
    get '/logout', to: 'devise/sessions#destroy', as: :logout
  end

  devise_for :users, skip: [:sessions]
  as :user do
    get '/login' => 'devise/sessions#new', as: :new_user_session
    post '/login' => 'devise/sessions#create', as: :user_session
    delete 'logout' => 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :user_friendships do
    member do
      put :accept
    end
  end

  resources :statuses #, path: 'updates'
  get 'feed', to: 'statuses#index', as: :feed

  root to: 'statuses#index'

  get '/:id', to: 'profiles#show', as:'profile'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Treebook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-fixed">
	<div class="navbar-inner">
		<div class="container">
			<a href="<%=root_path%>" class="navbar-brand">Treebook</a>
			<ul class="nav navbar-nav">
				<li><%= link_to "All Statuses", feed_path%></li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
			<% if user_signed_in? %>
				<li><%= link_to "Friends", user_friendships_path %></li>
				<li><%= link_to current_user.full_name, edit_user_registration_path %></li>
				<li><%= link_to "Logout", logout_path %> </li>
			<% else %>
				<li><%= link_to "Register", register_path %></li>
				<li><%= link_to "Login", login_path %> </li>
			<% end %>
			</ul>
		</div>
	</div>
</nav>	
	<div class="container">
	<% if notice %>
		<div class="alert alert-success">
		<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		<%= notice %>
		</div>
	<% end %>
	<% if alert %>
		<div class="alert alert-danger">
		<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			<%= alert %>
		</div>
	<% end %>
		<%= yield %>
	</div>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>